- name: Configure web root folder in Ubuntu
  when: ansible_distribution == "Ubuntu"
  copy: src=default dest=/etc/nginx/sites-available/default
  notify:
    - Restart nginx

- name: Configure web root folder in CentOS
  when: ansible_distribution == "CentOS"
  copy: src=default.conf dest=/etc/nginx/conf.d/default.conf
  notify:
    - Restart nginx
