---

- name: Install, Configure and deploy web page in nginx web server
  hosts: all
  vars:
     - greeting_msg: DevOps!
     - provisioner_tool: Docker
     - automation_tool: Ansible
  tasks:
    - name: Install nginx web server
      apt: name=nginx update_cache=yes state=latest

    - name: Create web root folder
      file: path=/var/html state=directory mode=0777

    - name: Configure nginx web root folder
      copy: src=default dest=/etc/nginx/sites-available/default

    - name: Restart the nginx web server
      #service: name=nginx state=restarted
      shell: service nginx restart

    - name: Deploy web page
      template: src=index.html.j2 dest=/var/html/index.html
 
...
