- name: Demonstrates creating containers from ansible playbook
  hosts: localhost
  tasks:
    - name: Create Ubuntu containers
      docker_container:
           name: "ubuntu{{item}}"
           hostname: "ubuntu{{item}}"
           image: "tektutor/ansible-ubuntu"
           ports:
             - "200{{item}}:22"
             - "800{{item}}:80"
           state: started
      with_sequence: start=1 end=5
