- name: Demonstrates use of dictionary variables and loops
  hosts: all 
  vars:
    proxy_conf:
       http_proxy: http://10.20.30.40:8080
       https_proxy: https://10.20.30.40:8080
  tasks:
    - name: Print http_proxy values
      debug: msg="{{item.key}} ==> {{item.value}}"
      with_dict: "{{proxy_conf}}"
